workspace = { members = ["proc-macro-authorization"] }
[package]
name = "api_manager"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.12.4", features = ["json"] }
tokio = { version = "1.38.0", features = ["full"] }
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.117"
thiserror = "1.0.61"
url = "2.5.0"
base64 = "0.22.1"
proc-macro-authorization = { path = "./proc-macro-authorization" }

[dev-dependencies]
toml = "0.8.14"
