[package]
name = "api_manager"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.12.2", features = ["json"] }
tokio = { version = "1.3.7", features = ["full"] }
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.114"
thiserror = "1.0.58"
derive_more = "0.99.17"
url = "2.5.0"

[dev-dependencies]
toml = "0.8.12"
